export const initialRecords = [
  {
    id: '1',
    name: 'Engine Check',
    date: '2025-07-20',
    status: 'Pending',
  },
  {
    id: '2',
    name: 'Oil Change',
    date: '2025-07-22',
    status: 'In Progress',
  },
  {
    id: '3',
    name: 'Brake Inspection',
    date: '2025-07-23',
    status: 'Completed',
  },
  {
    id: '4',
    name: 'Tire Rotation',
    date: '2025-07-24',
    status: 'Pending',
  },
  {
    id: '5',
    name: 'Battery Replacement',
    date: '2025-07-25',
    status: 'Completed',
  },
  {
    id: '6',
    name: 'Air Filter Check',
    date: '2025-07-26',
    status: 'In Progress',
  },
  {
    id: '7',
    name: 'AC Maintenance',
    date: '2025-07-27',
    status: 'Pending',
  },
  {
    id: '8',
    name: 'Fuel Injection Cleaning',
    date: '2025-07-28',
    status: 'Completed',
  },
  {
    id: '9',
    name: 'Transmission Service',
    date: '2025-07-29',
    status: 'Pending',
  },
  {
    id: '10',
    name: 'Coolant Flush',
    date: '2025-07-30',
    status: 'In Progress',
  },
  {
    id: '11',
    name: 'Wheel Alignment',
    date: '2025-08-01',
    status: 'Completed',
  },
  {
    id: '12',
    name: 'Headlight Adjustment',
    date: '2025-08-02',
    status: 'Pending',
  },
  {
    id: '13',
    name: 'Spark Plug Replacement',
    date: '2025-08-03',
    status: 'In Progress',
  },
  {
    id: '14',
    name: 'Exhaust Inspection',
    date: '2025-08-04',
    status: 'Completed',
  },
  {
    id: '15',
    name: 'Car Wash & Detailing',
    date: '2025-08-05',
    status: 'Pending',
  },
];
